#!/bin/bash
{
	#////////////////////////////////////
	# shaughvOS Cron.Daily script
	#
	#////////////////////////////////////
	#
	# Info:
	# - Location: /etc/cron.daily/shaughvos
	#
	#////////////////////////////////////

	# Assure that whiptail dialogues are skipped, even when the script is called manually, since STDOUT is redirected
	export G_INTERACTIVE=0

	#----------------------------------------------------------------
	# Main Loop
	#----------------------------------------------------------------
	# Sync system time if mode 2 (daily) is detected
	grep -q '^[[:blank:]]*CONFIG_NTP_MODE=2' /boot/shaughvos.txt && /boot/shaughvos/func/run_ntpd 1
	#----------------------------------------------------------------
	# Check for shaughvOS and/or APT updates
	APT_UPDATE_MODE=$(sed -n '/^[[:blank:]]*CONFIG_CHECK_APT_UPDATES=/{s/^[^=]*=//p;q}' /boot/shaughvos.txt)
	if grep -q '^[[:blank:]]*CONFIG_CHECK_SHAUGHVOS_UPDATES=1' /boot/shaughvos.txt
	then
		/boot/shaughvos/shaughvos-update 2
		[[ $APT_UPDATE_MODE == 2 && -f '/run/shaughvos/.update_available' ]] && { . /boot/shaughvos/func/shaughvos-globals; G_AGUP -f; }

	elif [[ $APT_UPDATE_MODE != 0 ]]
	then
		. /boot/shaughvos/func/shaughvos-globals
		G_AGUP -f
	fi
	# Apply APT upgrades if chosen and available
	[[ $APT_UPDATE_MODE == 2 && -f '/run/shaughvos/.apt_updates' ]] && apt-get -qq upgrade &> /var/tmp/shaughvos/logs/shaughvos-upgrade_apt.log
	#----------------------------------------------------------------
	# Sync shaughvOS-RAMlog to disk: https://github.com/RealEmmettS/shaughvOS/issues/4884
	systemctl -q is-enabled shaughvos-ramlog 2> /dev/null && /boot/shaughvos/func/shaughvos-ramlog 1
	#----------------------------------------------------------------
	# Refresh shaughvOS MOTD
	if [[ ! -f '/boot/shaughvos/.shaughvos-banner' ]] || grep -q '^[[:blank:]]*aENABLED\[12\]=1' /boot/shaughvos/.shaughvos-banner
	then
		[[ -f '/run/shaughvos/.shaughvos_motd' ]] && rm /run/shaughvos/.shaughvos_motd
		curl -sSfL 'https://raw.githubusercontent.com/RealEmmettS/shaughvOS/master/.update/motd' -o /run/shaughvos/.shaughvos_motd
	fi
	#----------------------------------------------------------------
	# shaughvOS-Backup daily
	if [[ -f '/boot/shaughvos/.shaughvos-backup_settings' ]] && grep -q '^[[:blank:]]*DAILY_BACKUP=1' /boot/shaughvos/.shaughvos-backup_settings
	then
		/boot/shaughvos/shaughvos-backup 1
	fi
	#----------------------------------------------------------------
	# shaughvOS-Sync daily
	if [[ -f '/boot/shaughvos/.shaughvos-sync_settings' ]] && grep -q '^[[:blank:]]*SYNC_CRONDAILY=1' /boot/shaughvos/.shaughvos-sync_settings
	then
		/boot/shaughvos/shaughvos-sync 1
	fi
	#----------------------------------------------------------------
	exit
	#----------------------------------------------------------------
} > /dev/null
