#!/bin/bash
{
	#////////////////////////////////////
	# shaughvOS Bug Report Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Location: /boot/shaughvos/shaughvos-bugreport
	# - Called from G_EXEC
	# - Generates a bug report as $G_HW_UUID.tar.xz/gz and saves it locally
	readonly USAGE='
Usage: shaughvos-bugreport <command>
Available commands:
  0, <empty>	Interactive menu to send or remove bug reports and review upload content
  1		Non-interactively send a bug report
 -1		Non-interactively remove an already uploaded bug report
'	#////////////////////////////////////

	# Import shaughvOS-Globals --------------------------------------------------------------
	. /boot/shaughvos/func/shaughvos-globals
	readonly G_PROGRAM_NAME='shaughvOS-BugReport'
	G_CHECK_ROOT_USER "$@"
	G_CHECK_ROOTFS_RW
	G_INIT
	# Import shaughvOS-Globals --------------------------------------------------------------

	# Grab input
	INPUT=$*

	readonly SFTP_ADDR='localhost' # Bug report upload disabled — shaughvOS saves reports locally
	readonly SFTP_USER='shaughvos-survey'
	readonly SFTP_PASS='upload2shaughvos'
	ext='gz'
	command -v xz > /dev/null && ext='xz'
	readonly UPLOAD_FILENAME="$G_HW_UUID.tar.$ext"
	readonly UPLOAD_FILESIZE_LIMIT=20000000 # bytes

	# List of commands we want to run to add their outputs to the upload archive
	readonly aCOMMAND_LIST=(

		'dpkg -l'
		'ip l'
		'ip a'
		'ip r'
		'lsusb'
		'cat /proc/cpuinfo'
		'free -m'
		'ps aux'
		'blkid'
		'mount'
		'df -Th'
		'ls /etc/rc*.d/'
		'cut -d: -f1 /etc/passwd'
		'locale'
		'ls -lAh /mnt' # shaughvos_userdata location
		'dmesg'
		'uname -a'
		'lsmod'
		'aplay -l'
		'aplay -L'
		'systemctl -l status *.service'
		'systemctl -l status *.mount'
		'/boot/shaughvos/shaughvos-services status'
	)

	# List of files and directories we want to add to the upload archive
	readonly aFILE_LIST=(

		# aCOMMAND_LIST output file
		'CMD_OUT.txt'

		# Git error template
		'G_EXEC_ERROR_REPORT'

		# Logs
		'/var/log'

		# Boot/kernel configs
		'/boot/firmware/config.txt' # RPi
		'/boot/firmware/cmdline.txt' # RPi
		'/boot/boot.ini' # Odroid C1/XU4
		'/boot/boot.scr'
		'/boot/shaughvosEnv.txt'
		'/boot/armbianEnv.txt' # Armbian

		# shaughvOS files
		'/boot/shaughvos.txt'
		'/boot/shaughvos'
		'/var/lib/shaughvos'
		'/var/tmp/shaughvos'
		'/run/shaughvos'

		# Login scripts
		# - bash shell
		'/etc/bash.bashrc'
		'/etc/bashrc.d'
		'/root/.bashrc'
		# - login shell
		'/etc/profile'
		'/etc/profile.d'
		'/root/.profile'

		# System
		'/etc/rc.local'
		'/etc/X11/xorg.conf'
		'/etc/X11/xorg.conf.d'
		'/etc/asound.conf'
		'/etc/network/interfaces'
		'/etc/network/interfaces.d'
		'/etc/wpa_supplicant/wpa_supplicant.conf'
		'/etc/fstab'
		'/etc/sysctl.conf'
		'/etc/sysctl.d'

		# Services
		'/etc/init.d'
		'/etc/systemd/system'
		'/lib/systemd/system'
		'/usr/local/lib/systemd/system'

		# APT
		'/etc/apt/sources.list'
		'/etc/apt/sources.list.d'
		'/etc/apt/preferences'
		'/etc/apt/preferences.d'
		'/etc/apt/apt.conf.d'
	)

	Generate_Upload_File()
	{
		G_SHAUGHVOS-NOTIFY 2 'Generating informative command outputs, please wait...'
		for i in "${aCOMMAND_LIST[@]}"
		do
			echo -e "\n----------\n$i\n----------"
			$i

		done &> CMD_OUT.txt

		# Copy the Git error template to working directory
		[[ -f '/tmp/G_EXEC_ERROR_REPORT' ]] && G_EXEC cp /tmp/G_EXEC_ERROR_REPORT G_EXEC_ERROR_REPORT

		# Allow warnings (exit code 1), e.g. when files are missing or could not be compressed (but have been added to the archive)
		G_EXEC_POST_FUNC(){ [[ $exit_code == 1 ]] && exit_code=0; }

		G_EXEC_DESC='Packing upload archive' G_EXEC tar -caf "$UPLOAD_FILENAME" --exclude='/var/log/journal/*' --ignore-failed-read "${aFILE_LIST[@]}"

		# Exit if size of upload archive exceeds limit
		(( $(stat -c '%s' "$UPLOAD_FILENAME") > $UPLOAD_FILESIZE_LIMIT )) || return 0

		G_SHAUGHVOS-NOTIFY 1 'The bug report upload archive appears to be unexpected large. Please inspect and in case clean up the locations to be uploaded, as their size should never be that large:'
		printf "%s\n" "${aFILE_LIST[@]}"
		exit 1
	}

	Upload_Bug_Report()
	{
		# Save bug report locally (remote upload is not available for shaughvOS)
		local report_dir='/var/tmp/shaughvos/bugreports'
		G_EXEC mkdir -p "$report_dir"

		if [[ $INPUT == 1 ]]
		then
			G_EXEC_DESC='Saving bug report locally'
			G_EXEC cp "$UPLOAD_FILENAME" "$report_dir/"
		else
			G_EXEC_DESC='Removing local bug report'
			G_EXEC rm -f "$report_dir/$UPLOAD_FILENAME"
			return 0
		fi

		G_SHAUGHVOS-NOTIFY 0 "Your bug report has been saved locally.
- Location: \e[33m$report_dir/$UPLOAD_FILENAME\e[0m
- Reference code: \e[33m$G_HW_UUID\e[0m
\nPlease file a related bug report at GitHub:
- https://github.com/RealEmmettS/shaughvOS/issues
\nAttach the bug report file from the location above to your GitHub issue.
\nTo remove the saved report, run:
- shaughvos-bugreport -1"
	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	# Interactive menu
	until [[ $INPUT ]]
	do
		G_WHIP_MENU_ARRAY=(

			'1' ': Send bug report archive to help the developers investigate an issue.'
			'2' ': Remove my previously uploaded bug report.'
			'3' ': Show me what is included with the upload archive.'
		)

		G_WHIP_BUTTON_CANCEL_TEXT='Exit' G_WHIP_MENU 'By sending a bug report file, you can help the developers to investigate your issue, in relation to your report on GitHub or the shaughvOS forum.
The file is sent via secured connection to our SFTP server and is stored there unreadable to the public upload user.
It will be removed automatically after 48 hours or when your issue has been solved, and you can remove it manually via this menu or by running:
- shaughvos-bugreport -1
\nWould you like to send a bug report or remove an already uploaded one?' || exit 0

		if (( $G_WHIP_RETURNED_VALUE == 1 )); then

			INPUT=1

		elif (( $G_WHIP_RETURNED_VALUE == 2 )); then

			INPUT=-1

		elif (( $G_WHIP_RETURNED_VALUE == 3 )); then

			G_WHIP_MSG "The upload will contain the following command outputs:
\n$(printf "\t- %s\n" "${aCOMMAND_LIST[@]}")
\nIt will contain as well the following files and directories:
\n$(printf "\t- %s\n" "${aFILE_LIST[@]}")"

		fi
	done

	if [[ $INPUT == 1 ]]
	then
		Generate_Upload_File

	elif [[ $INPUT == -1 ]]
	then
		# Send empty file to clear already uploaded bug report
		> "$UPLOAD_FILENAME"
	else
		G_SHAUGHVOS-NOTIFY 1 "Invalid input command ($INPUT). Aborting...\n$USAGE"
		exit 1
	fi

	Upload_Bug_Report

	#-----------------------------------------------------------------------------------
	exit 0
	#-----------------------------------------------------------------------------------
}
