#!/bin/bash
{
	#////////////////////////////////////
	# shaughvOS Survey Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@shaughvos.com / shaughvos.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Allows to send shaughvOS usage info via SFTP to shaughvOS server
	# - Includes hardware info, shaughvOS version+branch, installed software, benchmark results and some setup info
	# - No private data is sent, no one can identify you.
	# - Runs after every shaughvos-update and shaughvos-software install, if user opted in
	# - Summary can be visited at: https://shaughvos.com/survey/
	# - Allows the shaughvOS project to focus development based on popularity
	# - Further info: https://shaughvos.com/docs/shaughvos_tools/#shaughvos-survey
	#
	# Usage:
	# - /boot/shaughvos/shaughvos-survey		Interactive menu to opt in or out
	# - /boot/shaughvos/shaughvos-survey 1	Non-interactively send survey data or empty file, based on previous user choice
	#
	# File sent format: $G_HW_UUID.txt
	#////////////////////////////////////

	# Import shaughvOS-Globals --------------------------------------------------------------
	. /boot/shaughvos/func/shaughvos-globals
	readonly G_PROGRAM_NAME='shaughvOS-Survey'
	G_CHECK_ROOT_USER "$@"
	G_INIT
	# Import shaughvOS-Globals --------------------------------------------------------------

	# Grab input
	[[ $1 == 1 ]] && INPUT=1 || INPUT=0

	readonly FP_UPLOAD="$G_HW_UUID.txt"
	readonly SFTP_ADDR='ssh.shaughvos.com:29248'
	readonly SFTP_USER='shaughvos-survey'
	readonly SFTP_PASS='upload2shaughvos'

	Generate_File(){

		# shaughvOS version
		local version="$G_SHAUGHVOS_VERSION_CORE.$G_SHAUGHVOS_VERSION_SUB"

		# Current Git owner/branch
		local gitbranch="$G_GITOWNER/$G_GITBRANCH"

		# Active network interface
		local network_interface=$(G_GET_NET -q iface)
		[[ $network_interface ]] || network_interface='NONE'

		# Autostart index
		local autostart_index
		[[ -f '/boot/shaughvos/.shaughvos-autostart_index' ]] && read -r autostart_index < /boot/shaughvos/.shaughvos-autostart_index
		[[ $autostart_index ]] || autostart_index=0

		# rootfs on SD card/eMMC?
		local mmc=0
		[[ $G_ROOTFS_DEV == '/dev/mmcblk'* ]] && mmc=1

		cat << _EOF_ > "$FP_UPLOAD"
((aSHAUGHVOS_VERSION[$version]++))
((aGIT_BRANCH[$gitbranch]++))
((aDEVICE_NAME[$G_HW_MODEL_NAME]++))
((aCPU_ARCH[$G_HW_ARCH_NAME]++))
((aCPU_COUNT[$G_HW_CPU_CORES]++))
((aDISTRO_VERSION[$G_DISTRO_NAME]++))
((aAUTOSTART_OPTION[\${aAUTOSTART_NAME[$autostart_index]:=$autostart_index}]++))
((aAUTO_SETUP_AUTOMATED[$(grep -cm1 '^[[:blank:]]*AUTO_SETUP_AUTOMATED=1' /boot/shaughvos.txt)]++))
((aNETWORK_INTERFACE[$network_interface]++))
MMC=$mmc
_EOF_

		# RPi: Raspbian/Raspberry Pi OS (32-bit) or Debian/Raspberry Pi OS (64-bit)?
		(( $G_HW_MODEL < 10 )) && echo "((aRASPBIAN[$G_RASPBIAN]++))" >> "$FP_UPLOAD"

		# shaughvOS-Software installs
		[[ -f '/boot/shaughvos/.installed' ]] && while read -r software
		do
			software=${software##*[}
			software=${software%%]*}
			disable_error=1 G_CHECK_VALIDINT "$software" && echo "((aSOFTWARE[\${aSOFTWARE_NAME${G_SHAUGHVOS_VERSION_CORE}_${G_SHAUGHVOS_VERSION_SUB}[$software]:=$software}]++))" >> "$FP_UPLOAD"

		done < <(grep ']=2$' /boot/shaughvos/.installed)

		# shaughvOS-Benchmark results
		[[ -f '/var/lib/shaughvos/shaughvos-benchmark/results' ]] && cat /var/lib/shaughvos/shaughvos-benchmark/results >> "$FP_UPLOAD"

	}

	Send_File(){

		# Validate file name
		[[ $FP_UPLOAD =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.txt$ ]] || { G_SHAUGHVOS-NOTIFY 1 "Skipping sending/purging survey data as the survey UUID \"${FP_UPLOAD%.txt}\" is invalid..."; return 1; }

		# Check if our ssh.shaughvos.com SSH host key is present
		if [[ ! -f '/root/.ssh/known_hosts' ]] || ! grep -Eq '^\[?ssh.shaughvos.com(]:29248)?[[:blank:]]' /root/.ssh/known_hosts
		then
			# If missing, offer to re-add it
			if G_WHIP_YESNO '[WARNING] ssh.shaughvos.com SSH host key is missing\n\nOur ssh.shaughvos.com SSH host key, required to send or purge survey data and bug reports, is missing in /root/.ssh/known_hosts. Shall we re-create it to proceed with sending/purging the bug report?'
			then
				[[ -d '/root/.ssh' ]] || G_EXEC mkdir /root/.ssh
				[[ -f '/root/.ssh/known_hosts' ]] || > /root/.ssh/known_hosts
				G_CONFIG_INJECT '\[?ssh.shaughvos.com(]:29248)?[[:blank:]]' '[ssh.shaughvos.com]:29248 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJdEPlagpQ+RVHNOX3jkG1Bya7Oza1dAke8h8NszVW84' /root/.ssh/known_hosts
			else
				G_SHAUGHVOS-NOTIFY 1 'Skipping sending/purging survey data as our ssh.shaughvos.com SSH host key is missing in /root/.ssh/known_hosts...'
				return 1
			fi
		fi

		if (( $OPTED_IN ))
		then
			[[ -f $FP_UPLOAD ]] || Generate_File
		else
			# Send empty file to overwrite existing data, "rm" is not possible due to missing file list permissions
			> "$FP_UPLOAD"
		fi

		# Upload to server
		local timeout=$(sed -n '/^[[:blank:]]*CONFIG_G_CHECK_URL_TIMEOUT=/{s/^[^=]*=//p;q}' /boot/shaughvos.txt) G_EXEC_DESC='Sending survey data'
		(( $OPTED_IN )) || G_EXEC_DESC='Purging survey data'
		# - Timeout x2 for DNS resolving + connection, upload itself is done in no time
		G_EXEC_NOHALT=1 G_EXEC curl -m $(( ${timeout:-5} * 2 )) -sT "$FP_UPLOAD" "sftp://$SFTP_USER:$SFTP_PASS@$SFTP_ADDR/survey/"
		return $?

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	# Read opt in/out choice: 1=yes and send data | 0=no and purge data
	OPTED_IN=$(sed -n '/^[[:blank:]]*SURVEY_OPTED_IN=[01]$/{s/^[^=]*=//p;q}' /boot/shaughvos.txt)
	# - No (valid) choice done yet
	if [[ $OPTED_IN != [01] ]]
	then
		# Do not send data without user interactively opted in!
		OPTED_IN=0
		# Ask for choice, if interactive
		(( $G_INTERACTIVE )) && INPUT=0
	fi

	# Interactive menu
	until (( $INPUT ))
	do
		G_WHIP_MENU_ARRAY=(

			'Show' ': Show me the upload file content'
			'1' ': Opt IN and upload data'
			'0' ': Opt OUT and purge uploaded data'
		)

		G_WHIP_DEFAULT_ITEM=$OPTED_IN
		if G_WHIP_MENU 'shaughvOS-Survey would like to collect anonymous usage statistics.
This allows us to focus development based on popularity.
 - NO private data will be collected and NO ONE can identify you based on it.
 - The data is sent via secured SFTP connection, stored unreadable to the public upload user.
 - If you agree, your uploaded data will be updated after each shaughvOS-Update and shaughvOS-Software install.
 - Current survey statistics can be reviewed at: https://shaughvos.com/survey/
\nWould you like to join shaughvOS-Survey?'
		then
			if [[ $G_WHIP_RETURNED_VALUE == 'Show' ]]
			then
				Generate_File
				G_WHIP_VIEWFILE "$FP_UPLOAD"
				continue # Stay in loop
			else
				OPTED_IN=$G_WHIP_RETURNED_VALUE
				G_CONFIG_INJECT 'SURVEY_OPTED_IN=' "SURVEY_OPTED_IN=$OPTED_IN" /boot/shaughvos.txt
			fi
		fi

		break
	done

	# Send data if opted in or empty file if opted out
	Send_File

	#-----------------------------------------------------------------------------------
	exit $?
	#-----------------------------------------------------------------------------------
}
