---
# Partition configuration
efiSystemPartition: /boot/efi
efiSystemPartitionSize: 512M
efiSystemPartitionName: EFI

defaultFileSystemType: ext4

availableFileSystemTypes:
  - ext4
  - btrfs
  - xfs

allowManualPartitioning: true
initialPartitioningChoice: erase
initialSwapChoice: small

defaultPartitionTableType: gpt
