#!/bin/bash
{
	#////////////////////////////////////
	# shaughvOS Image creation/finalise Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	# Updated by MichaIng / micha@dietpi.com / dietpi.com
	# Clonezilla integration by sal666
	#
	#////////////////////////////////////
	# - Create new .img file from drive
	#   or use an existing .img file
	#   or use Clonezilla to generate a bootable installer ISO from drive for x86_64 systems
	# - Minimises root partition and filesystem
	# - Compresses the final image ready for release
	#////////////////////////////////////

	# Import shaughvOS-Globals ---------------------------------------------------------------
	if [[ -f '/boot/shaughvos/func/shaughvos-globals' ]]
	then
		. /boot/shaughvos/func/shaughvos-globals
	else
		[[ $G_GITOWNER && $G_GITBRANCH ]] || { echo '[FAILED] You must export or pass G_GITOWNER and G_GITBRANCH to the script'; exit 1; }
		curl -sSfo /tmp/shaughvos-globals "https://raw.githubusercontent.com/$G_GITOWNER/shaughvOS/$G_GITBRANCH/shaughvos/func/shaughvos-globals" || exit 1
		# shellcheck disable=SC1091
		. /tmp/shaughvos-globals
		G_EXEC rm /tmp/shaughvos-globals
		read -r debian_version < /etc/debian_version
		case $debian_version in
			'12.'*|'bookworm/sid') G_DISTRO=7;;
			'13.'*|'trixie/sid') G_DISTRO=8;;
			'14.'*|'forky/sid') G_DISTRO=9;;
			*) G_SHAUGHVOS-NOTIFY 1 "Unsupported distro version \"$debian_version\". Aborting ..."; exit 1;;
		esac
		# Ubuntu ships with /etc/debian_version from Debian testing, hence we assume one version lower.
		grep -q '^ID=ubuntu' /etc/os-release && ((G_DISTRO--))
		(( $G_DISTRO < 6 )) && { G_SHAUGHVOS-NOTIFY 1 'Unsupported Ubuntu version. Aborting ...'; exit 1; }
	fi
	readonly G_PROGRAM_NAME='shaughvOS-Imager'
	G_CHECK_ROOT_USER "$@"
	G_CHECK_ROOTFS_RW
	readonly FP_ORIGIN=$PWD # Store origin dir
	G_INIT
	G_EXEC cd "$FP_ORIGIN" # Process everything in origin dir instead of /tmp/$G_PROGRAM_NAME
	# Import shaughvOS-Globals ---------------------------------------------------------------

	readonly FP_MNT_TMP="/tmp/${G_PROGRAM_NAME}_mnt"
	readonly SHAUGHVOS_REPO="https://raw.githubusercontent.com/$G_GITOWNER/shaughvOS/$G_GITBRANCH"

	Error_Exit()
	{
		G_SHAUGHVOS-NOTIFY 1 "$1, aborting ..."
		exit 1
	}

	##########################################
	# Process inputs
	##########################################
	SOURCE_TYPE='Drive'
	FP_SOURCE_IMG=
	PART_TABLE_TYPE=
	#FP_ROOT_DEV=
	ROOT_FS_TYPE=
	#CLONING_TOOL=
	OUTPUT_IMG_EXT='img'
	#OUTPUT_IMG_NAME=
	[[ $MOUNT_IT == 'On' ]] || MOUNT_IT='Off'
	[[ $SKIP_FIRSTBOOT_RESIZE == 1 ]] || SKIP_FIRSTBOOT_RESIZE=0
	[[ $SHRINK_ONLY == 1 ]] || SHRINK_ONLY=0
	[[ $SKIP_ARCHIVE == 1 ]] || SKIP_ARCHIVE=0
	UPLOAD_SCRIPT=
	ADD_FAT_PART=0 # trailing FAT partition for first boot config files, automatically imported and partition removed on first boot
	CONFIGS_TO_BOOT=0 # for new RPi kernel/firmware stack where a boot FAT partition exists, but is mounted to /boot/firmware instead of /boot
	SIGN_PASS=
	RAW_HASH_SIZE=0 # store SHA256 and size for the uncompressed image, mainly used for Raspberry Pi Imager JSON
	while (( $# ))
	do
		case $1 in
			'--skip-archive') SKIP_ARCHIVE=1;;
			'--upload-script') shift; UPLOAD_SCRIPT=$1;;
			'--add-fat-part') ADD_FAT_PART=1;;
			'--configs-to-boot') CONFIGS_TO_BOOT=1;;
			'--sign') shift; SIGN_PASS=$1;;
			'--raw-hash-size') RAW_HASH_SIZE=1;;
			*)
				if [[ -b $1 ]]
				then
					FP_SOURCE=$1

				elif [[ -f $1 ]]
				then
					SOURCE_TYPE='Image'
					FP_SOURCE_IMG=$1

				elif [[ $1 ]]
				then
					Error_Exit "Input source $1 does not exist"
				fi
			;;
		esac
		shift
	done

	Unmount_tmp()
	{
		G_EXEC umount -R "$FP_MNT_TMP"
	}

	Delete_Loopback(){ [[ $FP_SOURCE_IMG ]] && losetup "$FP_SOURCE" &> /dev/null && G_EXEC losetup -d "$FP_SOURCE"; }

	# shellcheck disable=SC2329
	G_EXIT_CUSTOM()
	{
		findmnt "$FP_MNT_TMP" > /dev/null && Unmount_tmp
		[[ -d $FP_MNT_TMP ]] && G_EXEC rmdir "$FP_MNT_TMP"
		Delete_Loopback
		[[ -e 'tmpiso' ]] && G_EXEC rm -R tmpiso
	}

	Run_fsck()
	{
		if [[ $ROOT_FS_TYPE == 'ext4' ]]
		then
			G_EXEC_OUTPUT=1 G_EXEC e2fsck -fyD "$FP_ROOT_DEV"

		elif [[ $ROOT_FS_TYPE == 'f2fs' ]]
		then
			G_EXEC_OUTPUT=1 G_EXEC fsck.f2fs -f "$FP_ROOT_DEV"

		elif [[ $ROOT_FS_TYPE == 'btrfs' ]]
		then
			G_EXEC_OUTPUT=1 G_EXEC btrfs check --repair "$FP_ROOT_DEV"
		else
			Error_Exit "Unsupported root filesystem type ($ROOT_FS_TYPE)"
		fi
	}

	Menu_Source_Type()
	{
		main_menu_choice='Source type' # On cancel, keep this entry selected

		G_WHIP_MENU_ARRAY=(
			'Drive' ': The OS is stored on an attached drive.'
			'Image' ': The OS is stored as an image file.'
		)
		G_WHIP_DEFAULT_ITEM=$SOURCE_TYPE
		G_WHIP_MENU 'Please select how the input OS is stored:' || return 0
		SOURCE_TYPE=$G_WHIP_RETURNED_VALUE
		Delete_Loopback
		FP_SOURCE_IMG=
		FP_SOURCE=
		FP_ROOT_DEV=

		Menu_Source_Path # Directly open this menu next
	}

	Menu_Source_Path()
	{
		main_menu_choice='Source path' # On cancel, keep this entry selected

		if [[ $SOURCE_TYPE == 'Drive' ]]
		then
			# Detect drives with a partition table, containing a partition with and ext4, F2FS or Btrfs filesystem, excluding the hosts root filesystem drive
			mapfile -t G_WHIP_MENU_ARRAY < <(mawk -v root="$(lsblk -npo PKNAME "$G_ROOTFS_DEV")" '$1!=root && $2~/^(ext4|f2fs|btrfs)$/ {print $1"\n"$1"_details"}' < <(lsblk -rnpo PKNAME,FSTYPE) | sort -u)

			if [[ ! ${G_WHIP_MENU_ARRAY[0]} ]]
			then
				G_SHAUGHVOS-NOTIFY 1 'No drive with an ext4, F2FS or Btrfs formatted partition found, please retry ...'
				G_SHAUGHVOS-NOTIFY 2 'NB: This is the list of available block devices:'
				lsblk -npo NAME,SIZE,MAJ:MIN,FSTYPE,MOUNTPOINT,MODEL
				read -rp 'Press Enter or Return to return to menu...'
				return 1
			fi

			# Visually separate dev name and size and add model and serial
			for ((i=1;i<${#G_WHIP_MENU_ARRAY[@]};i+=2)); do G_WHIP_MENU_ARRAY[$i]=": $(lsblk -drno SIZE,MODEL,SERIAL "${G_WHIP_MENU_ARRAY[$i-1]}")"; done

			G_WHIP_DEFAULT_ITEM=$FP_SOURCE
			G_WHIP_MENU 'Please select the drive you wish to create the image from:
\nNB: All mounted partitions of the selected drive will be unmounted.' || return 0
			FP_SOURCE=$G_WHIP_RETURNED_VALUE
			FP_ROOT_DEV=

			G_SHAUGHVOS-NOTIFY 2 "Unmounting all filesystems below selected $FP_SOURCE ..."
			local mountpoint
			for i in "$FP_SOURCE"?*
			do
				mountpoint=$(findmnt -no TARGET "$i")
				[[ $mountpoint ]] && G_EXEC umount -R "$mountpoint"
			done
		else
			# Open shaughvOS-Explorer for image file selection
			/boot/shaughvos/shaughvos-explorer 1 || { G_SHAUGHVOS-NOTIFY 1 'No image file selected, please retry ...'; read -rp 'Press Enter or Return to return to menu ...'; return 1; }
			FP_SOURCE_IMG=$(</tmp/.shaughvos-explorer_selected_location)
			FP_ROOT_DEV=
			rm /tmp/.shaughvos-explorer_selected_location
			[[ -f $FP_SOURCE_IMG ]] || { G_SHAUGHVOS-NOTIFY 1 "Selected image file ($FP_SOURCE_IMG) does not exist, please retry ..."; read -rp 'Press Enter or Return to return to menu ...'; return 1; }

			# Create loop device from .img file
			Delete_Loopback # Prevent doubled loop device
			FP_SOURCE=$(losetup -f)
			G_EXEC_NOEXIT=1 G_EXEC losetup -P "$FP_SOURCE" "$FP_SOURCE_IMG" || return 1
			G_EXEC udevadm settle
			G_SHAUGHVOS-NOTIFY 0 "Attached the image ($FP_SOURCE_IMG) as loop device: $FP_SOURCE"
		fi

		Menu_Source_RootFS # Directly open this menu next
	}

	Menu_Source_RootFS()
	{
		main_menu_choice='Source rootfs' # On cancel, keep this entry selected

		# Detect partitions and list for selection
		# Coders NB: read/mapfile cannot be easily used here since we need to parse multiple lines and split at newline AND space.
		# shellcheck disable=SC2207
		G_WHIP_MENU_ARRAY=($(lsblk -rnpo NAME,FSTYPE "$FP_SOURCE"?* | mawk '$2~/^(ext4|f2fs|btrfs)$/'))
		# Visually separate dev name and size and add FS type
		for ((i=1;i<${#G_WHIP_MENU_ARRAY[@]};i+=2)); do G_WHIP_MENU_ARRAY[$i]=": $(lsblk -drno SIZE,FSTYPE "${G_WHIP_MENU_ARRAY[$i-1]}")"; done
		G_WHIP_DEFAULT_ITEM=$FP_ROOT_DEV
		G_WHIP_MENU 'Please select the OS root partition:' || return
		FP_ROOT_DEV=$G_WHIP_RETURNED_VALUE

		Menu_Target_Type # Directly open this menu next
	}

	Menu_Target_Type()
	{
		main_menu_choice='Target type' # On cancel, keep this entry selected

		G_WHIP_MENU_ARRAY=(
			'dd'         ': Create an .img file to flash to target system drive directly.'
			'Clonezilla' ': Create a live installer .iso with Calamares. (x86_64 only!)'
		)
		G_WHIP_DEFAULT_ITEM=$CLONING_TOOL
		G_WHIP_MENU 'Please select which cloning tool to use:
 - dd: A regular system image is created which must be flashed to the target system drive directly.
	This can be compared with regular SD card images like Raspbian Lite or Armbian ones.
	Usually those can be flashed to and booted from eMMC as well.
 - Clonezilla: A live installer ISO is created with the Calamares installer.
	Boot from the external drive to try shaughvOS live or install to any internal drive.
	Calamares handles partitioning and GRUB installation for the target hardware.
	NB: Only compatible with x86_64 systems!' || return
		CLONING_TOOL=$G_WHIP_RETURNED_VALUE
		[[ $CLONING_TOOL == 'dd' ]] && OUTPUT_IMG_EXT='img' || OUTPUT_IMG_EXT='iso'

		Menu_Target_Name # Directly open this menu next
	}

	Menu_Target_Name()
	{
		main_menu_choice='Target name' # On cancel, keep this entry selected

		G_WHIP_DEFAULT_ITEM=$OUTPUT_IMG_NAME
		G_WHIP_INPUTBOX 'Please enter a name for the new image file (without file extension):' || return
		OUTPUT_IMG_NAME=$G_WHIP_RETURNED_VALUE

		# Check for existing file, in case offer backup. Skip if source is image file and matches output file already.
		if [[ $PWD/$OUTPUT_IMG_NAME.$OUTPUT_IMG_EXT != "$FP_SOURCE_IMG" && -f $OUTPUT_IMG_NAME.$OUTPUT_IMG_EXT ]]
		then
			G_WHIP_BUTTON_OK_TEXT='Overwrite'
			G_WHIP_BUTTON_CANCEL_TEXT='Backup'
			G_WHIP_YESNO "[WARNING] $PWD/$OUTPUT_IMG_NAME.$OUTPUT_IMG_EXT already exists
\nDo you want to overwrite or backup the existing file to $PWD/$OUTPUT_IMG_NAME.$OUTPUT_IMG_EXT.bak?" || mv "$OUTPUT_IMG_NAME.$OUTPUT_IMG_EXT"{,.bak}
		fi

		main_menu_choice='Mount' # Select this entry next
	}

	Menu_Main()
	{
		G_WHIP_MENU_ARRAY=(
			'Source type' ": [${SOURCE_TYPE:=Drive}] Select how the input OS is stored"
			'Source path' ": [${FP_SOURCE_IMG:-$FP_SOURCE}] Select the input $SOURCE_TYPE"
		)
		[[ $FP_SOURCE ]] && G_WHIP_MENU_ARRAY+=('Source rootfs' ": [$FP_ROOT_DEV] Select input OS root partition")
		G_WHIP_MENU_ARRAY+=(
			'Target type' ": [${CLONING_TOOL:=dd}] Select output image type"
			'Target name' ": [${OUTPUT_IMG_NAME:=shaughvOS_RPi-ARMv8-Bookworm}] Choose the output image name"
			'' '●─'
			'Mount' ": [$MOUNT_IT] Review or edit drive content before image creation"
		)
		[[ $FP_SOURCE && $FP_ROOT_DEV ]] && G_WHIP_MENU_ARRAY+=('' '●─' 'Start' ": Start creating $OUTPUT_IMG_NAME.$OUTPUT_IMG_EXT")

		G_WHIP_DEFAULT_ITEM=$main_menu_choice
		G_WHIP_BUTTON_CANCEL_TEXT='Exit'
		G_WHIP_MENU 'Select input parameters and hit "Start" to continue image creation:' || exit 0

		case $G_WHIP_RETURNED_VALUE in
			'Source type') Menu_Source_Type;;
			'Source path') Menu_Source_Path;;
			'Source rootfs') Menu_Source_RootFS;;
			'Target type') Menu_Target_Type;;
			'Target name') Menu_Target_Name;;
			'Mount') [[ $MOUNT_IT == 'Off' ]] && MOUNT_IT='On' || MOUNT_IT='Off';;
			'Start') main_menu_choice='Start';;
			*) :;;
		esac
	}

	Main()
	{
		# Skip menu if all inputs are provided via environment variables
		if [[ ( $SOURCE_TYPE$FP_SOURCE == 'Drive'?* || $SOURCE_TYPE$FP_SOURCE_IMG == 'Image'?* ) && $FP_ROOT_DEV && $CLONING_TOOL =~ ^(dd|Clonezilla)$ && $OUTPUT_IMG_NAME ]]
		then
			if [[ $SOURCE_TYPE == 'Image' ]]
			then
				# Create loop device from .img file
				Delete_Loopback # Prevent doubled loop device
				FP_SOURCE=$(losetup -f)
				G_EXEC losetup -P "$FP_SOURCE" "$FP_SOURCE_IMG"
				G_SHAUGHVOS-NOTIFY 0 "Attached the image ($FP_SOURCE_IMG) as loop device: $FP_SOURCE"
				FP_ROOT_DEV="${FP_SOURCE}p${FP_ROOT_DEV: -1}"
			fi
			[[ $CLONING_TOOL == 'dd' ]] && OUTPUT_IMG_EXT='img' || OUTPUT_IMG_EXT='iso'
			G_SHAUGHVOS-NOTIFY 0 "\e[0mCreating minified image from:
- $SOURCE_TYPE: ${FP_SOURCE_IMG:-$FP_SOURCE}
- Root device: $FP_ROOT_DEV
- Via $CLONING_TOOL to $OUTPUT_IMG_NAME.$OUTPUT_IMG_EXT
- With intermediate mounting turned $MOUNT_IT"
		else
			local main_menu_choice
			Menu_Source_Type
			until [[ $main_menu_choice == 'Start' ]]
			do
				Menu_Main
			done
			unset -v main_menu_choice
		fi

		FP_FINAL="$FP_ORIGIN/$OUTPUT_IMG_NAME.$OUTPUT_IMG_EXT"

		# Flashing tools do not support xz-compressed ISOs
		[[ $OUTPUT_IMG_EXT == 'iso' ]] && SKIP_ARCHIVE=1

		# A trailing FAT partition does not make sense for Clonezilla embedded images
		[[ $CLONING_TOOL == 'Clonezilla' ]] && ADD_FAT_PART=0

		# Detect partition table type, failsafe detection of MBR to debug possibly other/unknown wording/partition table types
		PART_TABLE_TYPE=$(blkid -s PTTYPE -o value "$FP_SOURCE")
		if [[ $PART_TABLE_TYPE == 'dos' ]]
		then
			G_SHAUGHVOS-NOTIFY 2 'MBR partition table detected'

		elif [[ $PART_TABLE_TYPE == 'gpt' ]]
		then
			G_SHAUGHVOS-NOTIFY 2 'GPT partition table detected'
		else
			Error_Exit "Unknown partition table type ($PART_TABLE_TYPE)"
		fi

		# Detect root filesystem type
		ROOT_FS_TYPE=$(blkid -s TYPE -o value "$FP_ROOT_DEV")

		Run_fsck

		# Remount image for any required edits
		G_EXEC mkdir "$FP_MNT_TMP"
		G_EXEC mount "$FP_ROOT_DEV" "$FP_MNT_TMP"
		# - Remove bash history and DHCP data, which are stored on shutdown, hence cannot be removed via shaughvOS-Installer
		G_EXEC rm -f "$FP_MNT_TMP/"{root,home/*}/.bash_history "$FP_MNT_TMP/var/lib/dhcp{,cd}/"{,.}*
		# - Enable shaughvOS-FS_partition_resize to have both, old and new image being resized on next boot automatically
		if [[ $SKIP_FIRSTBOOT_RESIZE != 1 && -f $FP_MNT_TMP/etc/systemd/system/shaughvos-fs_partition_resize.service && ! -L $FP_MNT_TMP/etc/systemd/system/local-fs.target.wants/shaughvos-fs_partition_resize.service ]]
		then
			[[ -d $FP_MNT_TMP/etc/systemd/system/local-fs.target.wants ]] || G_EXEC mkdir "$FP_MNT_TMP/etc/systemd/system/local-fs.target.wants"
			G_EXEC ln -s {'/etc/systemd/system',"$FP_MNT_TMP/etc/systemd/system/local-fs.target.wants"}'/shaughvos-fs_partition_resize.service'
		fi
		if [[ $MOUNT_IT == 'On' ]] && G_WHIP_MSG "The ${SOURCE_TYPE,,} has been mounted to allow you reviewing or editing its content:
- $FP_ROOT_DEV > $FP_MNT_TMP
\nAn interactive bash subshell will open.
\nPlease use the \"exit\" command when you are finished, to return to $G_PROGRAM_NAME."
		then
			# Prevent shaughvos-login call in subshell
			local reallow_shaughvos_login=1
			[[ $G_SHAUGHVOS_LOGIN ]] && reallow_shaughvos_login=0
			export G_SHAUGHVOS_LOGIN=1
			G_EXEC cd "$FP_MNT_TMP"
			bash &> /dev/tty < /dev/tty
			G_EXEC cd "$FP_ORIGIN"
			(( $reallow_shaughvos_login )) && unset -v G_SHAUGHVOS_LOGIN
		fi
		Unmount_tmp

		# Dependencies
		local deps=('fdisk' 'zerofree')
		(( $SKIP_ARCHIVE )) || deps+=('xz-utils')
		if [[ $CLONING_TOOL == 'Clonezilla' ]]
		then
			deps+=('squashfs-tools' 'xorriso' 'isolinux' 'syslinux-common' 'syslinux-efi' 'grub-pc-bin' 'grub-efi-amd64-bin' 'mtools' 'dosfstools')

		elif [[ $PART_TABLE_TYPE == 'gpt' ]]
		then
			deps+=('gdisk')
		fi
		G_AGI "${deps[@]}"

		# Shrink last filesystem to minimum
		# - resize2fs: "Please run 'e2fsck -f /dev/loop0p1' first."
		Run_fsck
		local last_part_dev=$(sfdisk -lqo Device "$FP_SOURCE" | tail -1)
		# - If this is a tailing shaughvOS setup partition, remove it and let it be recreated freshly in case. This makes it easier for shaughvos-build to reuse the same image for multiple variants.
		if [[ $(blkid -s LABEL -o value "$last_part_dev") == 'SHAUGHVOS' ]]
		then
			G_EXEC_OUTPUT=1 G_EXEC sfdisk --delete "$FP_SOURCE" "${last_part_dev: -1}"
			last_part_dev=$(sfdisk -lqo Device "$FP_SOURCE" | tail -1)
		fi
		local last_fs_type=$(blkid -s TYPE -o value "$last_part_dev")
		if [[ $last_fs_type == 'ext'[234] ]]
		then
			if [[ $last_fs_type == 'ext'[34] ]] && tune2fs -l "$last_part_dev" | grep -q 'has_journal'
			then
				# Disable journal to allow further image size reduction and allow shaughvos-fs_partition_resize to re-create it with proper size based final filesystem size
				G_EXEC tune2fs -O '^has_journal' "$last_part_dev"
				G_EXEC sync
				G_SLEEP 1
			fi

			# Run multiple times until no change is done any more
			G_SHAUGHVOS-NOTIFY 2 'Shrinking last filesystem to minimum size...'
			local out last_fs_size=$(tune2fs -l "$last_part_dev" | mawk '/^Block count/{print $3;exit}') # blocks
			while :
			do
				resize2fs -Mp "$last_part_dev" 2>&1 | tee /tmp/resize2fs_out
				if out=$(grep -im1 'nothing to do!' /tmp/resize2fs_out)
				then
					rm /tmp/resize2fs_out
					FS_SIZE=$(mawk '{print $5}' <<< "$out") # blocks
					BLOCK_SIZE=${out%%k) *} BLOCK_SIZE=${BLOCK_SIZE##*\(} # KiB
					# Re-add 4 MiB if it would be still smaller than before, which was required on Raspbian Buster for successful boot, else leave original size
					if (( $last_fs_size > $FS_SIZE + 4096/$BLOCK_SIZE )) # blocks
					then
						FS_SIZE=$(( $FS_SIZE + 4096/$BLOCK_SIZE )) # blocks
						G_SHAUGHVOS-NOTIFY 0 "Reducing last filesystem size to $(( $FS_SIZE * $BLOCK_SIZE / 1024 + 1 )) MiB"
					else
						FS_SIZE=$last_fs_size
						G_SHAUGHVOS-NOTIFY 0 "Leaving last filesystem size at $(( $FS_SIZE * $BLOCK_SIZE / 1024 + 1 )) MiB"
					fi
					G_EXEC resize2fs "$last_part_dev" "$FS_SIZE"
					FS_SIZE=$(( $FS_SIZE * $BLOCK_SIZE * 2 )) # blocks => 512 byte sectors
					break

				elif out=$(grep -im1 'no such file or directory' /tmp/resize2fs_out)
				then
					Error_Exit 'Partition not found'
				fi
			done

		# F2FS does not support shrinking: https://www.reddit.com/r/archlinux/comments/bpp77f/shrinking_a_f2fs_partition/
		# Hence copy all data outside, remove and re-create a smaller filesystem, then copy data back in, as long as disk usage is not >=95% already.
		### The UUID changes and there is currently no way to change it back, hence only store current filesystem size and skip shrinking...
		elif [[ $last_fs_type == 'f2fs' ]] # && ! $(lsblk -rno FSUSE% "$last_part_dev") =~ ^(9[5-9]|100)%$ ]]
		then
			FS_SIZE=$(lsblk -rnbo SIZE "$last_part_dev") # bytes
			FS_SIZE=$(( $FS_SIZE / 512 )) # bytes => sectors
			#local usage=$(lsblk -rnbo FSUSED "$last_part_dev") # bytes
			#local sector_size=$(lsblk -rnbo LOG-SEC "$last_part_dev") # bytes
			#FS_SIZE=$(( ( $usage + 4*1024**2 ) / $sector_size )) # bytes + 4 MiB buffer => sectors
			#G_SHAUGHVOS-NOTIFY 2 'Copying last filesystem content to temporary directory'
			#G_EXEC mkdir "${FP_MNT_TMP}_backup"
			#G_EXEC mount -o ro "$last_part_dev" "$FP_MNT_TMP"
			#G_EXEC cp -a "$FP_MNT_TMP/." "${FP_MNT_TMP}_backup/"
			#G_EXEC umount "$FP_MNT_TMP"
			#G_SHAUGHVOS-NOTIFY 2 'Purging last filesystem'
			#G_EXEC dd if=/dev/zero of="$last_part_dev" bs=4K count=10
			#G_SHAUGHVOS-NOTIFY 2 'Re-creating smaller last filesystem' # Probably sload.f2fs can replace this? https://manpages.debian.org/sload.f2fs
			#G_EXEC_OUTPUT=1 G_EXEC mkfs.f2fs -w "$sector_size" "$last_part_dev" "$FS_SIZE"
			#G_SHAUGHVOS-NOTIFY 2 'Moving last filesystem content back'
			#G_EXEC mount "$last_part_dev" "$FP_MNT_TMP"
			#G_EXEC cp -a "${FP_MNT_TMP}_backup/." "$FP_MNT_TMP/"
			#G_EXEC rm -R "${FP_MNT_TMP}_backup"
			#Unmount_tmp
			#FS_SIZE=$(( $FS_SIZE * $sector_size / 512 )) # sectors => 512 bytes sectors

		elif [[ $last_fs_type == 'btrfs' ]]
		then
			G_SHAUGHVOS-NOTIFY 2 'Shrinking last filesystem to minimum size...'
			G_EXEC mount "$last_part_dev" "$FP_MNT_TMP"
			# Obtain current filesystem size
			local last_fs_size=$(findmnt -Ufnrbo SIZE -M "$FP_MNT_TMP") # bytes
			# Obtain minimal filesystem size + 4 MiB buffer
			FS_SIZE=$(( $(btrfs inspect-internal min-dev-size "$FP_MNT_TMP" | mawk '{print $1}') + 4*1024**2 )) # bytes
			# Shrink filesystem only if it would actually become smaller
			if (( $FS_SIZE < $last_fs_size ))
			then
				G_EXEC_OUTPUT=1 G_EXEC btrfs filesystem resize "$FS_SIZE" "$FP_MNT_TMP"
			else
				FS_SIZE=$last_fs_size
			fi
			Unmount_tmp
			FS_SIZE=$(( $FS_SIZE / 512 )) # bytes => 512 byte sectors
		fi

		G_SHAUGHVOS-NOTIFY 2 'Overriding filesystems free space with zeros to purge removed data and allow better compression...'
		while read -r path type
		do
			[[ $type ]] || continue
			if [[ $type == 'ext'[234] ]]
			then
				[[ ( -t 0 || -t 1 ) && $TERM != 'dumb' ]] && G_EXEC_OUTPUT=1
				G_EXEC zerofree -v "$path"
			else
				G_EXEC mount "$path" "$FP_MNT_TMP"
				G_EXEC_NOHALT=1 G_EXEC_OUTPUT=1 G_EXEC fstrim -v --quiet-unsupported "$FP_MNT_TMP"
				Unmount_tmp
			fi
			# shellcheck disable=SC2015
			[[ $path == "$FP_ROOT_DEV" ]] && Run_fsck || G_EXEC_OUTPUT=1 G_EXEC fsck -y "$path"

		done < <(lsblk -rnpo NAME,FSTYPE "$FP_SOURCE"?*)
		G_EXEC rmdir "$FP_MNT_TMP"

		# Only resize partition if new size would be lower
		if (( $(<"/sys/class/block/${last_part_dev##*/}/size") > $FS_SIZE ))
		then
			G_SHAUGHVOS-NOTIFY 2 "Shrinking last partition to: $(( $FS_SIZE / 2048 + 1 )) MiB"
			G_EXEC_OUTPUT=1 G_EXEC eval "sfdisk -N${last_part_dev: -1} '$FP_SOURCE' <<< ',$FS_SIZE'"
		fi

		# Derive target image size from last partition end
		# - WARNING: this assumes that the partitions in the table are in order (which we do in other places as well)
		local last_part_end=$(sfdisk -qlo End "$FP_SOURCE" | tail -1) # 512 byte sectors
		IMAGE_SIZE=$last_part_end
		# Add space for GPT backup partition table, or 1 sector for MBR
		if [[ $PART_TABLE_TYPE == 'gpt' ]]
		then
			# Obtain first usable LBA, which defines the size of the GPT backup, else use 34 sectors as default: https://github.com/RealEmmettS/shaughvOS/issues/7024
			local gpt_size=$(sfdisk -d "$FP_SOURCE" | mawk '/^first-lba/{print $2}')
			# shellcheck disable=SC2015
			(( $gpt_size )) && ((IMAGE_SIZE+=$gpt_size)) || ((IMAGE_SIZE+=34))
		else
			((IMAGE_SIZE++))
		fi
		((IMAGE_SIZE*=512)) # 512 byte sectors => bytes

		# RPi: Move configs to boot FAT partition to allow easier edit from Windows/macOS
		if (( $CONFIGS_TO_BOOT ))
		then
			local fat_mountpoint=$(mktemp -d)
			local root_mountpoint=$(mktemp -d)
			G_EXEC mount "${FP_ROOT_DEV::-1}1" "$fat_mountpoint"
			G_EXEC mount "$FP_ROOT_DEV" "$root_mountpoint"
			G_SHAUGHVOS-NOTIFY 2 'Copying shaughvos.txt and other config files to the boot partition'
			for f in 'shaughvos.txt' 'shaughvos-wifi.txt' 'Automation_Custom_PreScript.sh' 'Automation_Custom_Script.sh' 'unattended_pivpn.conf' 'shaughvos-k3s.yaml'
			do
				[[ -f $root_mountpoint/boot/$f ]] || continue
				G_EXEC cp "$root_mountpoint/boot/$f" "$fat_mountpoint/"
				TZ=UTC G_EXEC touch -t '197001010000' "$fat_mountpoint/$f"
				TZ=UTC G_EXEC touch -t '197001010001' "$root_mountpoint/boot/$f"
			done
			G_EXEC umount "$root_mountpoint" "$fat_mountpoint"
			G_EXEC rmdir "$root_mountpoint" "$fat_mountpoint"

		# Add trailing FAT partition to simplify first run setup if requested
		elif (( $ADD_FAT_PART ))
		then
			G_SHAUGHVOS-NOTIFY 2 'Adding a 1 MiB FAT partition to simplify first run setup'
			((IMAGE_SIZE+=1048576))
			# Increase source image size if required
			[[ $SOURCE_TYPE == 'Image' ]] && (( $(stat -c '%s' "$FP_SOURCE_IMG") < $IMAGE_SIZE )) && G_EXEC truncate -s "$IMAGE_SIZE" "$FP_SOURCE_IMG" && G_EXEC losetup -c "$FP_SOURCE"
			# Add new MBR partition
			local start=$(( $last_part_end + 1 ))
			local type='EBD0A0A2-B9E5-4433-87C0-68B6B72699C7' # https://en.wikipedia.org/wiki/GUID_Partition_Table#Partition_type_GUIDs
			[[ $PART_TABLE_TYPE == 'dos' ]] && type='c'
			G_EXEC eval "sfdisk -a '$FP_SOURCE' <<< 'start=$start,size=2048,type=$type'" # size in sectors
			# Create a FAT filesystem and add config files to it
			local new_fat_part=$(sfdisk -l "$FP_SOURCE" | mawk "/ $start /{print \$1;exit}")
			G_EXEC_OUTPUT=1 G_EXEC mkfs.fat -n SHAUGHVOS "$new_fat_part"
			local fat_mountpoint=$(mktemp -d)
			local root_mountpoint=$(mktemp -d)
			G_EXEC mount "$new_fat_part" "$fat_mountpoint"
			G_EXEC mount "$FP_ROOT_DEV" "$root_mountpoint"
			G_SHAUGHVOS-NOTIFY 2 'Copying shaughvos.txt and other config files to the SHAUGHVOS partition'
			for f in 'shaughvos.txt' 'shaughvos-wifi.txt' 'shaughvosEnv.txt' 'boot.ini' 'extlinux/extlinux.conf' 'Automation_Custom_PreScript.sh' 'Automation_Custom_Script.sh' 'unattended_pivpn.conf' 'shaughvos-k3s.yaml'
			do
				[[ -f $root_mountpoint/boot/$f ]] || continue
				G_EXEC cp "$root_mountpoint/boot/$f" "$fat_mountpoint/"
				TZ=UTC G_EXEC touch -t '202101010001' "$fat_mountpoint/${f#extlinux/}"
				TZ=UTC G_EXEC touch -t '202101010002' "$root_mountpoint/boot/$f"
			done
			cat << '_EOF_' > "$fat_mountpoint/README.txt"
shaughvOS config partition

This FAT partition is a place for relevant configuration files to pre-configure and automate your shaughvOS setup.
Those files will be copied into the root filesystem on first boot, if modified, to become effective, and the partition will be removed.

Apart of editing the existing files, you can also create the following for further automation:
- Automation_Custom_PreScript.sh
- Automation_Custom_Script.sh
- unattended_pivpn.conf
- shaughvos-k3s.yaml

For details, please check our documentation and shaughvos.txt itself:
https://dietpi.com/docs/usage/#how-to-do-an-automatic-base-installation-at-first-boot-shaughvos-automation
_EOF_
			G_EXEC umount "$root_mountpoint" "$fat_mountpoint"
			G_EXEC rmdir "$root_mountpoint" "$fat_mountpoint"
		fi

		# Exit now if source shall be shrunk only
		(( $SHRINK_ONLY )) && exit 0

		# Image file source and dd target
		if [[ $FP_SOURCE_IMG && $CLONING_TOOL == 'dd' ]]
		then
			# Clear loop
			Delete_Loopback

			G_SHAUGHVOS-NOTIFY 2 "Truncating final image file to actually used size: $(( $IMAGE_SIZE / 1024**2 + 1 )) MiB"
			G_EXEC truncate -s "$IMAGE_SIZE" "$FP_SOURCE_IMG"

			# Rename if source image != output image yet
			[[ $(realpath "$FP_FINAL") != "$(realpath "$FP_SOURCE_IMG")" ]] && G_EXEC mv "$FP_SOURCE_IMG" "$FP_FINAL"

			# Check for sufficient free disk space to store the xz archive with 100 MiB buffer
			(( $SKIP_ARCHIVE )) || G_CHECK_FREESPACE . $(( $IMAGE_SIZE * 15/100 / 1024**2 + 100 )) || exit 1

		# Drive source and dd target
		elif [[ $CLONING_TOOL == 'dd' ]]
		then
			# Check for sufficient free disk space to store the image and in case the xz archive with 100 MiB buffer
			local free_space_percent=100
			(( $SKIP_ARCHIVE )) || free_space_percent=115 # 15% image size for xz archive
			G_CHECK_FREESPACE . $(( $IMAGE_SIZE * $free_space_percent/100 / 1024**2 + 100 )) || exit 1

			G_SHAUGHVOS-NOTIFY 2 "Creating final image with actually used size: $(( $IMAGE_SIZE / 1024**2 + 1 )) MiB"
			G_EXEC_OUTPUT=1 G_EXEC dd if="$FP_SOURCE" of="$FP_FINAL" bs=1M status=progress count=$(( $IMAGE_SIZE / 1024**2 + 1 ))

		# Live ISO installer target (replaces Clonezilla)
		# Uses live-boot + Calamares for proper hardware-specific GRUB installation
		else
			G_SHAUGHVOS-NOTIFY 2 'Creating live installer ISO with Calamares'
			local live_root='/tmp/shaughvos-live-rootfs'
			[[ -e 'tmpiso' ]] && G_EXEC rm -R tmpiso

			### Step 1: Copy root filesystem to a larger temporary image ###
			# The imager has already shrunk and truncated the .img to minimum size.
			# We need a larger writable copy to install Calamares, live-boot, etc.
			G_SHAUGHVOS-NOTIFY 2 'Creating temporary root filesystem image (3 GiB)'
			G_EXEC dd if=/dev/zero of=/tmp/live-root.img bs=1M count=3072
			G_EXEC mkfs.ext4 -q -m0 /tmp/live-root.img
			G_EXEC mkdir -p "$live_root" /tmp/live-src
			G_EXEC mount "$FP_ROOT_DEV" /tmp/live-src -o ro
			G_EXEC mount /tmp/live-root.img "$live_root"
			G_SHAUGHVOS-NOTIFY 2 'Copying root filesystem to temporary image'
			G_EXEC_OUTPUT=1 G_EXEC cp -a /tmp/live-src/. "$live_root/"
			G_EXEC umount /tmp/live-src
			G_EXEC rmdir /tmp/live-src
			Delete_Loopback

			### Step 2: Install live-boot + Calamares into the root filesystem ###
			G_SHAUGHVOS-NOTIFY 2 'Installing live-boot and Calamares into root filesystem'
			G_EXEC mount --bind /dev "$live_root/dev"
			G_EXEC mount --bind /proc "$live_root/proc"
			G_EXEC mount --bind /sys "$live_root/sys"
			G_EXEC mount -t tmpfs tmpfs "$live_root/run"
			# Ensure DNS works inside chroot
			G_EXEC cp /etc/resolv.conf "$live_root/etc/resolv.conf"
			G_EXEC_DESC='Installing live-boot, Calamares, LightDM, and display/input drivers' G_EXEC_OUTPUT=1 G_EXEC chroot "$live_root" bash -c \
				'apt-get update && apt-get install -y --no-install-recommends live-boot calamares calamares-settings-debian polkitd lightdm lightdm-gtk-greeter xserver-xorg-video-fbdev xserver-xorg-video-vesa xserver-xorg-input-libinput plymouth plymouth-themes'

			### Step 3: Copy shaughvOS Calamares config (overrides Debian defaults) ###
			G_SHAUGHVOS-NOTIFY 2 'Copying shaughvOS Calamares configuration'
			G_EXEC mkdir -p "$live_root/etc/calamares/branding/shaughvos" "$live_root/etc/calamares/modules"
			G_EXEC curl -sSf "$SHAUGHVOS_REPO/assets/calamares/settings.conf" -o "$live_root/etc/calamares/settings.conf"
			G_EXEC curl -sSf "$SHAUGHVOS_REPO/assets/calamares/branding/shaughvos/branding.desc" -o "$live_root/etc/calamares/branding/shaughvos/branding.desc"
			G_EXEC curl -sSf "$SHAUGHVOS_REPO/assets/shaughv-logo.svg" -o "$live_root/etc/calamares/branding/shaughvos/shaughv-logo.svg"
			for f in unpackfs.conf bootloader.conf finished.conf users.conf partition.conf welcome.conf services-systemd.conf shellprocess.conf displaymanager.conf; do
				G_EXEC curl -sSf "$SHAUGHVOS_REPO/assets/calamares/modules/$f" -o "$live_root/etc/calamares/modules/$f"
			done

			### Step 4: Add Calamares desktop autostart + shortcut ###
			G_EXEC curl -sSf "$SHAUGHVOS_REPO/assets/calamares/calamares-installer.desktop" -o "$live_root/etc/xdg/autostart/calamares-installer.desktop"
			G_EXEC mkdir -p "$live_root/usr/share/applications"
			G_EXEC cp "$live_root/etc/xdg/autostart/calamares-installer.desktop" "$live_root/usr/share/applications/"

			### Step 5: Install Node.js/npm and Claude Code CLI ###
			G_SHAUGHVOS-NOTIFY 2 'Installing Node.js, npm, and Claude Code CLI'
			G_EXEC_OUTPUT=1 G_EXEC chroot "$live_root" bash -c \
				'apt-get install -y --no-install-recommends nodejs npm && curl -fsSL https://claude.ai/install.sh | bash || true'

			# Rebuild initramfs to ensure live-boot hooks are included after all package installs
			chroot "$live_root" update-initramfs -u 2>/dev/null || true

			# Register shaughvOS Plymouth theme and rebuild initramfs to include it
			chroot "$live_root" bash -c \
				'if [[ -f /usr/share/plymouth/themes/shaughvos/shaughvos.plymouth ]]; then
					plymouth-set-default-theme shaughvos
					update-initramfs -u
				fi' 2>/dev/null || true

			### Step 5b: Prepare root filesystem for live-boot compatibility ###
			G_SHAUGHVOS-NOTIFY 2 'Preparing root filesystem for live-boot mode'
			# Clear fstab — live-boot generates mounts dynamically, Calamares regenerates on install
			echo '# Live boot — fstab generated dynamically' > "$live_root/etc/fstab"
			# Disable services that expect a real installed disk (not available in live mode)
			chroot "$live_root" systemctl disable shaughvos-fs_partition_resize 2>/dev/null || true
			chroot "$live_root" systemctl disable shaughvos-firstboot 2>/dev/null || true
			chroot "$live_root" systemctl disable shaughvos-preboot 2>/dev/null || true
			chroot "$live_root" systemctl disable shaughvos-postboot 2>/dev/null || true
			chroot "$live_root" systemctl disable shaughvos-ramlog 2>/dev/null || true
			# Disable root's getty autologin — the live session uses lightdm for admin, not root's startx
			rm -f "$live_root/etc/systemd/system/getty@tty1.service.d/shaughvos-autologin.conf"
			rm -f "$live_root/etc/systemd/system/console-getty.service.d/shaughvos-autologin.conf"
			# Mark setup as complete — prevents shaughvos-login from entering first-run/error mode
			echo 2 > "$live_root/boot/shaughvos/.install_stage"
			# Set passwords for live session (admin + root)
			chroot "$live_root" bash -c "echo 'admin:1234' | chpasswd"
			chroot "$live_root" bash -c "echo 'root:1234' | chpasswd"
			# Grant admin passwordless sudo for the live session (required for Calamares + desktop command)
			# Also preserve display-related env vars so GUI apps work under sudo
			cat > "$live_root/etc/sudoers.d/live-admin" << 'SUDOERS'
admin ALL=(ALL:ALL) NOPASSWD: ALL
Defaults env_keep += "DISPLAY XAUTHORITY XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS"
SUDOERS
			chmod 0440 "$live_root/etc/sudoers.d/live-admin"
			# Set desktop autostart mode for the live session
			echo 2 > "$live_root/boot/shaughvos/.shaughvos-autostart_index"
			# Guarantee greeter wallpaper exists — always download fresh from GitHub.
			# Don't trust the base image's copy (curl || true could have silently failed).
			G_EXEC mkdir -p "$live_root/usr/share/backgrounds/shaughvos"
			G_EXEC curl -sSfLo "$live_root/usr/share/backgrounds/shaughvos/desktop_background.jpg" "https://raw.githubusercontent.com/${G_GITOWNER:-RealEmmettS}/shaughvOS/${G_GITBRANCH:-master}/assets/desktop_background.jpg"
			# Ensure desktop autologin for the live session
			G_EXEC mkdir -p "$live_root/etc/lightdm/lightdm.conf.d"
			cat > "$live_root/etc/lightdm/lightdm.conf.d/live-autologin.conf" << 'AUTOLOGIN'
[Seat:*]
autologin-user=admin
autologin-session=xfce
AUTOLOGIN
			# Set persistent Xfce session default for installed system — live-autologin.conf (which includes
			# autologin-session=xfce) gets removed by Calamares shellprocess. Without an explicit
			# user-session, LightDM may fail to start any session, causing a login loop.
			cat > "$live_root/etc/lightdm/lightdm.conf.d/50-shaughvos.conf" << 'SHAUGHVOS_SESSION'
[Seat:*]
user-session=xfce
session-wrapper=/usr/local/bin/shaughvos-xsession-wrapper
SHAUGHVOS_SESSION
			# Diagnostic session wrapper — logs session startup info for debugging login loops
			cat > "$live_root/usr/local/bin/shaughvos-xsession-wrapper" << 'XWRAPPER'
#!/bin/sh
# shaughvOS X session wrapper — logs session startup for diagnostics
LOG="/var/log/lightdm/shaughvos-session.log"
echo "=== Session start: $(date) ===" >> "$LOG" 2>/dev/null
echo "User: $(whoami) (UID: $(id -u))" >> "$LOG" 2>/dev/null
echo "DISPLAY=$DISPLAY" >> "$LOG" 2>/dev/null
echo "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR" >> "$LOG" 2>/dev/null
echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS" >> "$LOG" 2>/dev/null
echo "Session arg: $1" >> "$LOG" 2>/dev/null
echo "--- xsessions available ---" >> "$LOG" 2>/dev/null
ls -la /usr/share/xsessions/ >> "$LOG" 2>/dev/null
echo "--- critical packages ---" >> "$LOG" 2>/dev/null
dpkg -l xfce4-session dbus-user-session dbus-x11 lightdm 2>/dev/null | tail -5 >> "$LOG" 2>/dev/null
echo "--- starting session ---" >> "$LOG" 2>/dev/null
exec /etc/X11/Xsession "$@"
XWRAPPER
			chmod +x "$live_root/usr/local/bin/shaughvos-xsession-wrapper"
			chroot "$live_root" systemctl enable lightdm 2>/dev/null || true
			# Belt and suspenders: create the display-manager symlink directly in case systemctl enable failed in chroot
			ln -sf /lib/systemd/system/lightdm.service "$live_root/etc/systemd/system/display-manager.service"
			# Live mode guard — suppresses Calamares autostart when booted with shaughvos.live=1
			# Fail-safe: if this script fails, Calamares launches (install mode behavior).
			# The /usr/share/applications/ copy of the .desktop is NOT removed — user can still
			# launch "Install shaughvOS" from the Applications menu in live mode.
			cat > "$live_root/usr/local/bin/shaughvos-live-check" << 'LIVECHECK'
#!/bin/sh
# If shaughvos.live=1 is in the kernel cmdline, remove Calamares autostart
# so the user gets a plain desktop without the installer launching.
LOG="/var/log/shaughvos-live-check.log"
echo "=== Live check: $(date) ===" >> "$LOG" 2>/dev/null
echo "cmdline: $(cat /proc/cmdline)" >> "$LOG" 2>/dev/null
if grep -q 'shaughvos\.live=1' /proc/cmdline 2>/dev/null; then
    echo "Live mode detected — suppressing Calamares autostart" >> "$LOG" 2>/dev/null
    rm -f /etc/xdg/autostart/calamares-installer.desktop
else
    echo "Install mode — Calamares autostart preserved" >> "$LOG" 2>/dev/null
fi
LIVECHECK
			chmod +x "$live_root/usr/local/bin/shaughvos-live-check"
			# Systemd service runs the guard before LightDM starts the desktop
			cat > "$live_root/etc/systemd/system/shaughvos-live-check.service" << 'LIVESVC'
[Unit]
Description=shaughvOS live mode check
Before=lightdm.service display-manager.service
After=local-fs.target
DefaultDependencies=no

[Service]
Type=oneshot
ExecStart=/usr/local/bin/shaughvos-live-check
RemainAfterExit=yes

[Install]
WantedBy=graphical.target
LIVESVC
			chroot "$live_root" systemctl enable shaughvos-live-check 2>/dev/null || true
			# Configure LightDM greeter — desktop wallpaper background, Makira font, Dracula theme
			G_EXEC mkdir -p "$live_root/etc/lightdm"
			cat > "$live_root/etc/lightdm/lightdm-gtk-greeter.conf" << 'GREETER'
[greeter]
background = /usr/share/backgrounds/shaughvos/desktop_background.jpg
font-name = Makira Medium 10
theme-name = Dracula
icon-theme-name = Papirus-Dark
indicators = ~host;~spacer;~clock;~spacer;~session;~power
GREETER
			# Disable xfwm4 compositor — crashes on VirtualBox with nomodeset (no hardware GL),
			# producing visual glitch + session crash -> login loop. Enforced here as safety net
			# over the base image's shaughvos-software-generated config.
			G_EXEC mkdir -p "$live_root/etc/xdg/xfce4/xfconf/xfce-perchannel-xml"
			cat > "$live_root/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml" << 'XFWM4'
<?xml version="1.0" encoding="UTF-8"?>
<channel name="xfwm4" version="1.0">
  <property name="general" type="empty">
    <property name="theme" type="string" value="Dracula"/>
    <property name="title_font" type="string" value="Makira SemiBold 10"/>
    <property name="use_compositing" type="bool" value="false"/>
  </property>
</channel>
XFWM4
			# Set system-wide fontconfig defaults — Makira for sans-serif UI, IBM Plex Mono for monospace
			G_EXEC mkdir -p "$live_root/etc/fonts"
			cat > "$live_root/etc/fonts/local.conf" << 'FONTCONF'
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>sans-serif</family>
    <prefer><family>Makira</family></prefer>
  </alias>
  <alias>
    <family>sans</family>
    <prefer><family>Makira</family></prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer><family>IBM Plex Mono</family></prefer>
  </alias>
  <alias>
    <family>serif</family>
    <prefer><family>Makira</family></prefer>
  </alias>
</fontconfig>
FONTCONF
			# Set graphical.target as default so systemd starts lightdm on boot (base image defaults to multi-user.target)
			chroot "$live_root" systemctl set-default graphical.target 2>/dev/null || ln -sf /lib/systemd/system/graphical.target "$live_root/etc/systemd/system/default.target"
			# Add nomodeset + quiet splash to GRUB defaults — carries to installed system via squashfs.
			# nomodeset: VirtualBox vmwgfx errors without it; quiet splash: enables Plymouth boot splash.
			# (quiet splash intentionally omitted from live ISO boot entry per v1.8.7 for install diagnostics)
			sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="consoleblank=0"/GRUB_CMDLINE_LINUX_DEFAULT="consoleblank=0 nomodeset quiet splash"/' "$live_root/etc/default/grub"
			# Create Calamares launcher script — uses sudo -E to preserve DISPLAY/XAUTHORITY,
			# xhost to grant root X11 access, and software rendering for VirtualBox compatibility.
			# Every major distro avoids bare "sudo calamares" because sudo strips env vars.
			cat > "$live_root/usr/local/bin/launch-calamares" << 'LAUNCHER'
#!/bin/bash
xhost +si:localuser:root 2>/dev/null
exec sudo -E env LIBGL_ALWAYS_SOFTWARE=1 /usr/bin/calamares "$@"
LAUNCHER
			chmod +x "$live_root/usr/local/bin/launch-calamares"
			# Add polkit rule for password-free admin access in the live session
			G_EXEC mkdir -p "$live_root/etc/polkit-1/rules.d"
			cat > "$live_root/etc/polkit-1/rules.d/49-shaughvos-live.rules" << 'POLKIT'
polkit.addRule(function(action, subject) {
    if (subject.user === "admin") {
        return polkit.Result.YES;
    }
});
POLKIT

			### Step 6: Create staging directory for ISO ###
			G_SHAUGHVOS-NOTIFY 2 'Creating ISO staging directory'
			mkdir -p tmpiso/{live,isolinux,boot/grub/x86_64-efi,EFI/BOOT}

			### Step 7: Copy kernel + initramfs from the root filesystem ###
			G_SHAUGHVOS-NOTIFY 2 'Extracting kernel and initramfs'
			# shellcheck disable=SC2086
			cp "$live_root"/boot/vmlinuz-* tmpiso/live/vmlinuz
			# shellcheck disable=SC2086
			cp "$live_root"/boot/initrd.img-* tmpiso/live/initrd

			# Mark plymouth as manually installed so autoremove doesn't remove it
			chroot "$live_root" apt-mark manual plymouth plymouth-themes 2>/dev/null || true
			# Clean apt caches before squashfs to reduce ISO size
			chroot "$live_root" apt-get clean 2>/dev/null || true
			chroot "$live_root" apt-get autoremove -y 2>/dev/null || true
			# Clear apt lists (will be regenerated on first apt-get update)
			rm -rf "$live_root/var/cache/apt/archives"/*.deb "$live_root/var/lib/apt/lists"/* 2>/dev/null || true

			### Step 8: Create squashfs of the root filesystem ###
			# Unmount bind mounts before squashfs creation
			umount "$live_root/run" "$live_root/sys" "$live_root/proc" "$live_root/dev" 2>/dev/null || true
			G_EXEC_DESC='Creating squashfs filesystem (this takes several minutes)' G_EXEC_OUTPUT=1 G_EXEC mksquashfs \
				"$live_root" tmpiso/live/filesystem.squashfs \
				-comp zstd -Xcompression-level 15 -no-exports -noappend

			### Step 9: Unmount and clean up temporary image ###
			G_EXEC umount "$live_root"
			G_EXEC rmdir "$live_root"
			G_EXEC rm /tmp/live-root.img

			### Step 10: Create GRUB config for UEFI boot ###
			# Download shaughvOS background for boot menu
			G_EXEC curl -sSf "$SHAUGHVOS_REPO/.build/images/Clonezilla/shaughvos-background_768p.png" -o tmpiso/boot/grub/shaughvosbg.png
			cat << '_EOF_' > tmpiso/boot/grub/grub.cfg
insmod all_video
insmod gfxterm
insmod png

set gfxmode=auto
set gfxpayload=keep
terminal_output gfxterm

if background_image /boot/grub/shaughvosbg.png; then
    true
fi

set default=0
set timeout=30
set menu_color_normal=white/black
set menu_color_highlight=white/dark-gray

menuentry "Install shaughvOS" {
    search --no-floppy --set=root --label SHAUGHVOS
    linux ($root)/live/vmlinuz boot=live nomodeset
    initrd ($root)/live/initrd
}
menuentry "Try shaughvOS (without installing)" {
    search --no-floppy --set=root --label SHAUGHVOS
    linux ($root)/live/vmlinuz boot=live nomodeset quiet splash shaughvos.live=1
    initrd ($root)/live/initrd
}
menuentry "Power off" {
    halt
}
_EOF_
			G_EXEC cp tmpiso/boot/grub/grub.cfg tmpiso/EFI/BOOT/grub.cfg

			### Step 11: Create embedded GRUB config for EFI ###
			cat << '_EOF_' > /tmp/grub-embed.cfg
if ! [ -d "$cmdpath" ]; then
    if regexp --set=1:isodevice '^(\([^)]+\))\/?[Ee][Ff][Ii]\/[Bb][Oo][Oo][Tt]\/?$' "$cmdpath"; then
        cmdpath="${isodevice}/EFI/BOOT"
    fi
fi
configfile "${cmdpath}/grub.cfg"
_EOF_

			### Step 12: Create isolinux config for BIOS boot ###
			# Download shaughvOS background for BIOS boot menu
			G_EXEC curl -sSf "$SHAUGHVOS_REPO/.build/images/Clonezilla/shaughvos-background_480p.png" -o tmpiso/isolinux/shaughvosbg.png
			cat << '_EOF_' > tmpiso/isolinux/isolinux.cfg
UI vesamenu.c32

MENU TITLE shaughvOS
MENU BACKGROUND shaughvosbg.png
DEFAULT install
TIMEOUT 300

MENU COLOR border       30;44   #40ffffff #a0000000 std
MENU COLOR title        1;36;44 #9033ccff #a0000000 std
MENU COLOR sel          7;37;40 #e0ffffff #20ffffff all
MENU COLOR unsel        37;44   #50ffffff #a0000000 std

LABEL install
  MENU LABEL Install shaughvOS
  MENU DEFAULT
  KERNEL /live/vmlinuz
  APPEND initrd=/live/initrd boot=live nomodeset

LABEL live
  MENU LABEL Try shaughvOS (without installing)
  KERNEL /live/vmlinuz
  APPEND initrd=/live/initrd boot=live nomodeset quiet splash shaughvos.live=1

LABEL poweroff
  MENU LABEL Power off
  COM32 poweroff.c32
_EOF_

			### Step 13: Copy boot loader files ###
			G_SHAUGHVOS-NOTIFY 2 'Setting up boot loaders'
			G_EXEC cp /usr/lib/ISOLINUX/isolinux.bin tmpiso/isolinux/
			G_EXEC cp /usr/lib/syslinux/modules/bios/* tmpiso/isolinux/
			G_EXEC cp -r /usr/lib/grub/x86_64-efi/* tmpiso/boot/grub/x86_64-efi/

			### Step 14: Create EFI boot image ###
			G_EXEC_DESC='Creating EFI boot image' G_EXEC_OUTPUT=1 G_EXEC grub-mkstandalone -O x86_64-efi \
				--modules='part_gpt part_msdos fat iso9660' \
				--locales='' --themes='' --fonts='' \
				--output=tmpiso/EFI/BOOT/BOOTx64.EFI \
				"boot/grub/grub.cfg=/tmp/grub-embed.cfg"
			G_EXEC rm /tmp/grub-embed.cfg
			(
				cd tmpiso || exit 1
				dd if=/dev/zero of=efiboot.img bs=1M count=20 2>/dev/null
				mkfs.vfat efiboot.img > /dev/null
				mmd -i efiboot.img ::/EFI ::/EFI/BOOT
				mcopy -vi efiboot.img EFI/BOOT/BOOTx64.EFI boot/grub/grub.cfg ::/EFI/BOOT/ > /dev/null
			)

			### Step 15: Generate the ISO ###
			G_EXEC_DESC="Generating $FP_FINAL" G_EXEC_OUTPUT=1 G_EXEC xorriso \
				-as mkisofs -iso-level 3 \
				-o "$FP_FINAL" \
				-full-iso9660-filenames \
				-volid 'SHAUGHVOS' \
				-publisher 'shaughvOS; https://github.com/RealEmmettS/shaughvOS;' \
				--mbr-force-bootable -partition_offset 16 \
				-joliet -joliet-long -rational-rock \
				-isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
				-eltorito-boot isolinux/isolinux.bin \
					-no-emul-boot -boot-load-size 4 -boot-info-table \
					--eltorito-catalog isolinux/isolinux.cat \
				-eltorito-alt-boot \
					-e --interval:appended_partition_2:all:: \
					-no-emul-boot -isohybrid-gpt-basdat \
				-append_partition 2 C12A7328-F81F-11D2-BA4B-00A0C93EC93B tmpiso/efiboot.img \
				tmpiso
			G_EXEC rm -R tmpiso
		fi

		# Move GPT backup partition table to end of drive
		[[ $CLONING_TOOL != 'Clonezilla' && $PART_TABLE_TYPE == 'gpt' ]] && G_EXEC_DESC='Re-creating GPT backup partition table and header at end of image' G_EXEC_OUTPUT=1 G_EXEC sgdisk -e "$FP_FINAL"

		# Generate hashes, size info and compress image if requested
		local result_text="\nImage file:  $FP_FINAL"
		local upload_list=()
		if (( $RAW_HASH_SIZE ))
		then
			G_EXEC_DESC='Generating image size file' G_EXEC eval "stat -c '%s' '$FP_FINAL' > '$FP_FINAL.size'"
			result_text+="\nImage size:  $FP_FINAL.size"
			upload_list+=("$FP_FINAL.size")
		fi
		if (( $SKIP_ARCHIVE ))
		then
			G_EXEC_DESC='Generating image hash' G_EXEC eval "sha256sum '$OUTPUT_IMG_NAME.$OUTPUT_IMG_EXT' > '$FP_FINAL.sha256'"
			result_text+="\nImage hash:  $FP_FINAL.sha256"
			upload_list+=("$FP_FINAL" "$FP_FINAL.sha256")
		else
			if (( $RAW_HASH_SIZE ))
			then
				G_EXEC_DESC='Generating image hash' G_EXEC eval "sha256sum '$OUTPUT_IMG_NAME.$OUTPUT_IMG_EXT' > '$FP_FINAL.sha256'"
				result_text+="\nImage hash:  $FP_FINAL.sha256"
				upload_list+=("$FP_FINAL.sha256")
			fi
			[[ -f $FP_FINAL.xz ]] && G_EXEC rm "$FP_FINAL.xz"
			G_EXEC_DESC='Generating xz-compressed image' G_EXEC xz -9e -T0 -M75% -k "$FP_FINAL"
			result_text+="\nxz file:     $FP_FINAL.xz"
			upload_list+=("$FP_FINAL.xz")

			G_EXEC_DESC='Generating xz hash' G_EXEC eval "sha256sum '$OUTPUT_IMG_NAME.$OUTPUT_IMG_EXT.xz' > '$FP_FINAL.xz.sha256'"
			result_text+="\nxz hash:     $FP_FINAL.xz.sha256\n$(<"$FP_FINAL.xz.sha256")"
			upload_list+=("$FP_FINAL.xz.sha256")
			FP_FINAL+='.xz'
		fi

		# Generate GPG signature if requested
		if [[ $SIGN_PASS ]]
		then
			G_SHAUGHVOS-NOTIFY 2 "Signing $FP_FINAL ..."
			gpg --batch --pinentry-mode loopback --passphrase "$SIGN_PASS" -b --armor "$FP_FINAL" || Error_Exit 'Signing failed, please check your signing key and passphase'
			result_text+="\nSignature:   $FP_FINAL.asc\n$(<"$FP_FINAL.asc")"
			upload_list+=("$FP_FINAL.asc")
		fi

		G_SHAUGHVOS-NOTIFY 0 "shaughvOS-Imager has successfully finished.$result_text"

		# Upload if requested
		if [[ $UPLOAD_SCRIPT ]]
		then
			[[ -x "$UPLOAD_SCRIPT" ]] || Error_Exit "Upload script $UPLOAD_SCRIPT does not exist or is not executable"
			G_EXEC_OUTPUT=1 G_EXEC ./upload.sh "${upload_list[@]}"
		fi
	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main
	#/////////////////////////////////////////////////////////////////////////////////////
	Main
	#-----------------------------------------------------------------------------------
	exit 0
	#-----------------------------------------------------------------------------------
}
