.TH SHAUGHVOS-CONFIG 1 "April 2026" "shaughvOS" "shaughvOS Tools"
.SH NAME
shaughvos-config \- shaughvOS configuration menu
.SH SYNOPSIS
.B shaughvos-config
.RI [ SECTION ]
.SH DESCRIPTION
.B shaughvos-config
is the TUI for configuring a shaughvOS system. It covers locale,
hostname, network, passwords, display, audio, CPU governor,
services, autostart, and more.
.PP
Invoking the command without arguments launches the top-level menu.
Passing a section name jumps directly to that submenu.
.SH OPTIONS
See
.B shaughvos-config \-\-help
for the full list of sections and flags.
.SH SEE ALSO
.BR shaughvos (1),
.BR shaughvos-software (1),
.BR shaughvos-update (1)
.SH AUTHOR
Emmett Shaughnessy
.SH HOMEPAGE
https://github.com/RealEmmettS/shaughvOS
