.TH SPEEDQX 1 "April 2026" "shaughvOS" "QubeTX 300 Series"
.SH NAME
speedqx \- QubeTX quad-provider speed test
.SH SYNOPSIS
.B speedqx
.RI [ OPTIONS ]
.SH DESCRIPTION
.B speedqx
runs internet speed tests against four providers concurrently and
reports download throughput, upload throughput, latency, and a
bufferbloat grade.
.PP
.B speedqx
is shipped as part of the ND-300 package (see
.BR nd300 (1)).
.SH OPTIONS
See
.B speedqx \-\-help
for the full list of flags and modes.
.SH SEE ALSO
.BR shaughvos (1),
.BR nd300 (1),
.BR tr300 (1),
.BR sd300 (1)
.SH AUTHOR
QubeTX \- a department of ES Development LLC.
Bundled with shaughvOS.
.SH HOMEPAGE
https://github.com/QubeTX/qube-network-diagnostics
