#!/bin/bash
{
	#////////////////////////////////////
	# shaughvOS Function: Change the system hostname
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@shaughvos.com / shaughvos.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Location: /boot/shaughvos/func/change_hostname
	# - Usage: /boot/shaughvos/func/change_hostname <hostname>
	#////////////////////////////////////

	# Import shaughvOS-Globals --------------------------------------------------------------
	. /boot/shaughvos/func/shaughvos-globals
	readonly G_PROGRAM_NAME='shaughvOS-Change_hostname'
	G_CHECK_ROOT_USER "$@"
	G_CHECK_ROOTFS_RW
	G_INIT
	# Import shaughvOS-Globals --------------------------------------------------------------

	# Set hostname if valid: https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_hostnames
	EXIT_CODE=1
	if [[ $* =~ ^[[:alnum:]][[:alnum:].-]*[[:alnum:]]$ ]]
	then
		G_EXEC hostname "$*"
		G_EXEC eval "echo '$*' > /etc/hostname"
		G_CONFIG_INJECT '127.0.1.1[[:blank:]]' "127.0.1.1 $*" /etc/hosts
		G_CONFIG_INJECT 'AUTO_SETUP_NET_HOSTNAME=' "AUTO_SETUP_NET_HOSTNAME=$*" /boot/shaughvos.txt
		EXIT_CODE=0
	else
		G_SHAUGHVOS-NOTIFY 1 "Invalid hostname input ($*). Aborting..."
		G_SHAUGHVOS-NOTIFY 0 'Further info: https://en.wikipedia.org/wiki/Hostname#Syntax'
	fi

	#-----------------------------------------------------------------------------------
	exit "$EXIT_CODE"
	#-----------------------------------------------------------------------------------
}
