#!/bin/bash
{
	#////////////////////////////////////
	# shaughvOS Function:
	# - Synchronise system clock with network time
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@shaughvos.com / shaughvos.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Launched by shaughvos-postboot.service, daily or hourly cron job based on CONFIG_NTP_MODE shaughvos.txt setting
	# - Launches systemd-timesyncd.service for network time sync
	#
	# Usage:
	# - /boot/shaughvos/func/run_ntpd
	# - /boot/shaughvos/func/run_ntpd 1 | Force new sync despite success flag
	#////////////////////////////////////

	# Import shaughvOS-Globals --------------------------------------------------------------
	. /boot/shaughvos/func/shaughvos-globals
	readonly G_PROGRAM_NAME='shaughvOS-TimeSync'
	G_CHECK_ROOT_USER "$@"
	#G_INIT
	# Import shaughvOS-Globals --------------------------------------------------------------

	readonly INPUT=$*
	readonly FP_FLAG='/run/systemd/timesync/synchronized'
	readonly CONFIG_NTP_MODE=$(sed -n '/^[[:blank:]]*CONFIG_NTP_MODE=/{s/^[^=]*=//p;q}' /boot/shaughvos.txt)

	Run_TimeSync()
	{
		# Forced mode: Restart service to force a resync
		if [[ $INPUT == 1 ]]
		then
			[[ -f $FP_FLAG ]] && G_EXEC rm "$FP_FLAG"
			G_EXEC systemctl restart systemd-timesyncd

		# Regular mode: Do not restart service to not abort a sync in progress on boot or concurrent execution
		else
			G_EXEC systemctl start systemd-timesyncd
		fi

		# Loop until success or G_INTERACTIVE=0 timeout
		declare -r MAX_LOOPS_CHECK=${MAX_LOOPS_CHECK:-60} # seconds
		while (( $EXIT_CODE ))
		do
			for ((i=1; i<=$MAX_LOOPS_CHECK; i++))
			do
				# Check for flag
				if [[ -f $FP_FLAG ]]
				then
					G_SHAUGHVOS-NOTIFY 0 'Time sync completed'
					EXIT_CODE=0
					break 2

				elif (( $i < $MAX_LOOPS_CHECK ))
				then
					G_SHAUGHVOS-NOTIFY 2 "Waiting for time sync ($i/$MAX_LOOPS_CHECK)"
					G_SLEEP 1
				else
					G_SHAUGHVOS-NOTIFY 1 'Time sync timed out'

					G_WHIP_MENU_ARRAY=(

						'Retry' ': (Recommended) Rerun network time sync'
						'NTP mirror' ': Change the NTP mirror used'
						'Override' ': (NOT RECOMMENDED) Ignore failure and override time sync status'
					)

					G_WHIP_DEFAULT_ITEM='Retry'
					G_WHIP_MENU 'Network time sync has not yet completed or failed to update.\nTo prevent issues with outdated system time during installations, please select an option below.\n
NB: We highly recommend choosing "Retry" first. Failing that, try to change the "NTP mirror".\n"Override" is a last resort and may cause follow-up issues due to incorrect system clock time.' || break 2

					if [[ $G_WHIP_RETURNED_VALUE == 'NTP mirror' ]]
					then
						G_WHIP_MSG 'shaughvOS-Config will now be launched on the next screen:\n - Select "NTP Mirror"\n - Select a different NTP mirror\n\nOnce completed, exit shaughvos-config to resume.'
						/boot/shaughvos/shaughvos-config 16

					elif [[ $G_WHIP_RETURNED_VALUE == 'Override' ]]
					then
						EXIT_CODE=0
						break 2
					fi
				fi
			done

			# Start service again in case it failed: This has no effect when running already.
			G_EXEC systemctl start systemd-timesyncd
		done

		# Stop service on oneshot modes, but recreate flag on success which is removed on service stop
		(( $CONFIG_NTP_MODE < 4 )) || return "$EXIT_CODE"
		G_EXEC systemctl stop systemd-timesyncd
		(( $EXIT_CODE == 0 )) || return "$EXIT_CODE"
		G_EXEC mkdir -p /run/systemd/timesync
		> "$FP_FLAG"
	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	# Manual mode: Skip time sync
	if [[ $CONFIG_NTP_MODE != [1-4] ]]
	then
		G_SHAUGHVOS-NOTIFY 2 'Manual mode detected, skipping time sync'

	# Regular mode and success flag exists: Run only once per boot session
	elif [[ $INPUT != 1 && -f $FP_FLAG ]]
	then
		# Stop service on oneshot modes: https://github.com/RealEmmettS/shaughvOS/issues/5256
		(( $CONFIG_NTP_MODE < 4 )) && systemctl -q is-active systemd-timesyncd || exit 0
		G_EXEC systemctl stop systemd-timesyncd
		G_EXEC mkdir -p /run/systemd/timesync
		> "$FP_FLAG"

	# Container: Skip time sync
	elif (( $G_HW_MODEL == 75 )) || grep -zaq '^container=' /proc/1/environ
	then
		G_SHAUGHVOS-NOTIFY 2 'Container detected, skipping time sync'

	# Forced mode or flag does not exist: Sync
	else
		EXIT_CODE=1
		Run_TimeSync
		# Print additional info on failure
		(( $EXIT_CODE == 0 )) || G_SHAUGHVOS-NOTIFY 2 'Please check the service logs for more information:\n - journalctl -u systemd-timesyncd'
		exit "$EXIT_CODE"
	fi

	#-----------------------------------------------------------------------------------
	exit 0
	#-----------------------------------------------------------------------------------
}
